name: XLua Build

on: [push]

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        msbuild xlua.vcxproj /p:Platform=x64 /p:Configuration=Release /m
        mkdir jenkins\build_products
        move Release\plugins\win_x64/xlua.pdb jenkins\build_products\xlua_win.pdb
        move Release\plugins\win_x64/xlua.xpl jenkins\build_products\xlua_win.xpl
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: xlua_win
        path: |
          jenkins\build_products
        if-no-files-found: error
          
  build-mac:
    runs-on: macos-11
    env:
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: yes
      - name: Setup Credentials
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.APPLE_DEV_CERTIFICATE }}
          p12-password: ${{ secrets.APPLE_DEV_CERTIFICATE_PASSWORD }}
      - name: Build
        run: |
          ./jenkins_driver.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xlua_mac
          path: |
            jenkins/build_products/xlua_mac.xpl
          if-no-files-found: error
          
  build-linux:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/x-plane/xlua_builder:latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: |
          ./jenkins_driver.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xlua_lin
          path: |
            jenkins/build_products/xlua_lin.xpl
          if-no-files-found: error
